open Parser

let pprint_lexer_token ppf token =
  Fmt.pf
    ppf
    "%s"
    (match token with
     | INT i -> Fmt.str "INT: %d@." i
     | LID lid -> Fmt.str "LID: %s@." lid
     | UID uid -> Fmt.str "UID: %s@." uid
     | LPAREN -> "("
     | RPAREN -> ")"
     | COMMA -> ","
     | COLON -> ":"
     | SEMICOLON -> ";"
     | ADD -> "+"
     | SUB -> "-"
     | MUL -> "*"
     | DIV -> "/"
     | MOD -> "%%"
     | NOT -> "!"
     | BORROWED -> "^"
     | ASSIGN -> "="
     | LT -> "<"
     | GT -> ">"
     | BAR -> "|"
     | UNDERSCORE -> "_"
     | LEQ -> "<="
     | GEQ -> ">="
     | EQ -> "=="
     | NEQ -> "!="
     | AND -> "&&"
     | OR -> "||"
     | ARROW -> "->"
     | UNIT -> "()"
     | OF -> "of"
     | FST -> "fst"
     | SND -> "snd"
     | IF -> "if"
     | THEN -> "then"
     | ELSE -> "else"
     | ENDIF -> "endif"
     | TRUE -> "true"
     | FALSE -> "false"
     | LET -> "let"
     | REC -> "rec"
     | FUN -> "fun"
     | IN -> "in"
     | BEGIN -> "begin"
     | END -> "end"
     | TYPE -> "type"
     | MATCH -> "match"
     | DMATCH -> "match!"
     | ENDMATCH -> "endmatch"
     | WITH -> "with"
     | SOME -> "Some"
     | NONE -> "None"
     | EOF -> "eof"
     | TYPE_INT -> "int"
     | TYPE_BOOL -> "bool"
     | TYPE_UNIT -> "unit"
     | TYPE_OPTION -> "option")
;;
